services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - pg-store:/var/lib/postgresql/data

volumes:
  pg-store:
